/*
 * usage.h -- the option summary, exactly as Apple's tool prints it.
 *
 * Generated from the real tool's output rather than retyped: it is a
 * hundred and thirty lines of text whose every column has to match, and
 * a transcription error would be invisible until a diff caught it.
 *
 * Copyright (c) 2026 Sunneva N. Mariu <sunnevanattsol@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef TEXTURECONVERTER_USAGE_H
#define TEXTURECONVERTER_USAGE_H

static const char *const tc_usage[] = {
	"",
	"Options:",
	"--ASTC_HDR                   - Decode KTX ASTC images as HDR.",
	"--alpha_mode=value           - Alpha mode (default: \"Ignore\").",
	"--alpha_reference=value      - Alpha reference for alpha to coverage (default: \"0.950000\").",
	"--alpha_to_coverage          - Use alpha to coverage.",
	"--alpha_weight               - Use alpha weight when compressing.",
	"--build_array                - Build a 2D texture array by combining input textures. Can not be combined with --build_cubemap, --build_volume or --build_mips.",
	"--build_cubemap              - Build a cubemap by combining input textures. Input textures should be specified in +X/-X/+Y/-Y/+Z/-Z order. Can not be combined with --build_array, --build_volume or --build_mips.",
	"--build_mips                 - Build a 2D mip mapped image by combining input textures. Only 2D source images can be combined and each image must be half the width and height of the previous image. Can not be combined with --build_array, --build_cubemap or --build_volume.",
	"--build_volume               - Build a volume by combining input textures. Can not be combined with --build_array, --build_cubemap or --build_mips.",
	"--channel_weighting=value    - Channel weighting (default: \"Perceptual\").",
	"--check_date                 - Compare the date/time of the source file to the output file (if present) & skip compression if the output file is newer. Can be combined with --check_details.",
	"--check_details              - Compare the compression options and TextureConverter version against the output file (if present) & skip compression if not needed. Only supported for KTX files. Can be combined with --check_date.",
	"--compare=value              - Comparison file path (default: \"\").",
	"--compression_format=value   - Compression format (default: \"None\").",
	"--compression_quality=value  - Compression quality (default: \"Production\").",
	"--compressor=value           - Compressor library (default: \"Auto\").",
	"--crop_uniform_content       - Crop images with uniform content.",
	"--decompressed=value         - Decompressed file path (default: \"\").",
	"--decompression_format=value - Decompression format (default: \"Auto\").",
	"--decompressor=value         - Decompressor library (default: \"Auto\").",
	"--disable_annotation         - Disable KTX file annotation.",
	"--disable_multithreading     - Disable multithreading.",
	"--file_format=value          - File format (default: \"Auto\").",
	"--flip_x                     - Flip image along x-axis.",
	"--flip_y                     - Flip image along y-axis.",
	"--flip_z                     - Flip image along z-axis.",
	"--format=value               - Format (default: \"None\").",
	"--gamma_in=value             - Gamma for input image, \"sRGB\" or float value. (default: \"1.000000\").",
	"--gamma_out=value            - Gamma for output texture, \"sRGB\" or float value. (default: \"1.000000\").",
	"--gamut_in=value             - Color gamut of input texture. (default: \"\").",
	"--gamut_out=value            - Color gamut for output texture. (default: \"\").",
	"--max_extent=value           - Maximum image extent (default: \"16384\").",
	"--max_mipmaps=value          - Maximum number of mipmaps. If set to 0 uses the number of mipmaps in the intput texture (default: \"15\").",
	"--metrics                    - Report error metrics.",
	"--mipmap_filter=value        - Filter for mipmap generation (default: \"Kaiser\").",
	"--mode=value                 - Operation mode (default: \"Compress\").",
	"--normal_map                 - Treat image as normal map.",
	"--output=value               - Output file path (default: \"\").",
	"--progressbar                - Display progress bar.",
	"--pvrtc_punch_through=value  - PVRTC punch through mode (default: \"Unused\").",
	"--resize_filter=value        - Resize filter (default: \"Mitchell\").",
	"--resize_round_mode=value    - Resize round mode (default: \"None\").",
	"--rgbm_encoding              - Use RGBM encoding.",
	"--rgbm_range=value           - Range for RGBM encoding (default: \"6.000000\").",
	"--scale_range                - Scale image to entire color range.",
	"--srgb_format                - Use sRGB pixel format.",
	"--time                       - Output processing time in milliseconds.",
	"--verbose                    - Verbose output.",
	"--wrap_mode=value            - Wrap mode (default: \"Mirror\").",
	"",
	"Compressors:",
	"Auto, ARM, ETC2COMP, ISPC, NVTT, PVRTC, STB.",
	"",
	"Decompressors:",
	"Auto, ARM, GPU, NVTT, PVRTC.",
	"",
	"Uncompressed formats:",
	"BGRA8, R16, R32, R8, RG16, RG32, RG8, RGB16, RGB32, RGB8, RGBA16, RGBA32, RGBA8.",
	"",
	"ARM compression formats:",
	"ASTC10x10, ASTC10x10_HDR, ASTC10x5, ASTC10x5_HDR, ASTC10x6, ASTC10x6_HDR, ASTC10x8, ASTC10x8_HDR, ASTC12x10, ASTC12x10_HDR, ASTC12x12, ASTC12x12_HDR, ASTC4x4, ASTC4x4_HDR, ASTC5x4, ASTC5x4_HDR, ASTC5x5, ASTC5x5_HDR, ASTC6x5, ASTC6x5_HDR, ASTC6x6, ASTC6x6_HDR, ASTC8x5, ASTC8x5_HDR, ASTC8x6, ASTC8x6_HDR, ASTC8x8, ASTC8x8_HDR.",
	"",
	"ETC2COMP compression formats:",
	"EAC_R11, EAC_RG11, EAC_RGBA8, ETC2_RGB8, ETC2_RGB8A1.",
	"",
	"ISPC compression formats:",
	"ASTC4x4, ASTC5x4, ASTC5x5, ASTC6x5, ASTC6x6, ASTC8x5, ASTC8x6, ASTC8x8, BC1, BC3, BC4, BC5, BC6U, BC7, ETC2_RGB8.",
	"",
	"NVTT compression formats:",
	"BC1, BC2, BC3, BC4, BC5, BC6S, BC6U, BC7, EAC_R11, EAC_RGBA8, ETC2_RGB8.",
	"",
	"PVRTC compression formats:",
	"PVRTC_RGBA_2BPP, PVRTC_RGBA_4BPP, PVRTC_RGB_2BPP, PVRTC_RGB_4BPP.",
	"PVRTC support in Metal is now deprecated. Usage of ASTC/ETC2/BC formats is recommended instead.",
	"",
	"STB compression formats:",
	"BC1, BC3, BC4, BC5.",
	"",
	"Input file formats:",
	"BMP, DDS, EXR, HDR, HEIC, JPG, KTX, KTX2, PNG, TGA, TIFF, WEBP.",
	"",
	"Output file formats:",
	"Auto, Auto, DDS, EXR, H, KTX, KTX2.",
	"",
	"Operation modes:",
	"Compare, Compress, Convert, Decompress, Examine.",
	"",
	"Compression qualities:",
	"Fastest, Highest, Normal, Production.",
	"",
	"Alpha modes:",
	"Ignore, Premultiply, Preserve.",
	"",
	"Color gamuts:",
	"DisplayP3, sRGB.",
	"",
	"Channel weighting modes:",
	"Linear, Perceptual.",
	"",
	"Resize filters:",
	"Box, Kaiser, Mitchell, Triangle.",
	"",
	"Resize round modes:",
	"NearestMultipleOfFour, NearestPowerOfTwo, NextMultipleOfFour, NextPowerOfTwo, None, PreviousMultipleOfFour, PreviousPowerOfTwo.",
	"",
	"Mipmap filters:",
	"Box, Kaiser, Triangle.",
	"",
	"Wrap modes:",
	"Clamp, Mirror, Repeat.",
	"",
	"PVRTC punch through modes:",
	"Allowed, Forced, Unused.",
	"",
	"",
	"Examples",
	"========",
	"",
	"To compress a source file to ASTC4x4 at highest quality with mip-maps:",
	"\tTextureConverter --compression_format=ASTC4x4 --compression_quality=Highest --output=Output.ktx2 Input.png",
	"",
	"To compress a source file to BC1 at highest quality with no mip-maps:",
	"\tTextureConverter --max_mipmaps=1 --compression_format=BC1 --compression_quality=Highest --output=Output.ktx2 Input.png",
	"",
	"To build a cube map from multiple source files:",
	"\tTextureConverter --mode=convert --build_cubemap --output=Cubemap.ktx2 X_Pos.png X_Neg.png Y_Pos.png Y_Neg.png Z_Pos.png Z_Neg.png",
	"",
	"To build a volume texture from multiple source files and compress to BC1:",
	"\tTextureConverter --compression_format=BC1 --build_volume --output=Volume.ktx2 Slice1.png Slice2.png Slice3.png Slice4.png",
	"",
	"To decompress a source file:",
	"\tTextureConverter --mode=decompress --output=Output.ktx2 Input.ktx2",
	"",
	"To compare two images:",
	"\tTextureConverter --mode=compare --compare=Input2.ktx2 Input1.ktx2",
	"",
	NULL
};

#endif /* TEXTURECONVERTER_USAGE_H */
