# ld -- Apple's Mach-O linker (ld64).
#
# Sources are discovered across ld/, ld/parsers/, ld/passes/ and
# mach_o/.  The generated headers below stand in for the script phases
# in ld64.xcodeproj.
.include "${TOP}/mk/with-ld64.mk"

T_SRCS!=	cd ${TOP} && ls src/dist-dev-tools/ld64/src/ld/*.cpp \
		    src/dist-dev-tools/ld64/src/ld/parsers/*.cpp \
		    src/dist-dev-tools/ld64/src/ld/passes/*.cpp \
		    src/dist-dev-tools/ld64/src/ld/passes/stubs/*.cpp \
		    src/dist-dev-tools/ld64/src/mach_o/*.cpp \
		    src/dist-dev-tools/ld64/src/ld/*.c 2>/dev/null
T_SRCS+=	build/gen/ld64/version.c

# --- generated headers ------------------------------------------------
#
# ld64.xcodeproj produces these with script phases; we reproduce them.

# configure.h, from src/create_configure.  That script emits
# SUPPORT_ARCH_riscv32 0 whenever TOOLCHAIN_INSTALL_DIR matches
# XcodeDefault -- which is exactly the toolchain we build -- so riscv32
# is off here too.
${LD64_GEN}/configure.h:
	@mkdir -p ${LD64_GEN}
	@{ \
	  for a in i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7em \
		   armv7k arm64 arm64e arm64_32 armv8m; do \
	    echo "#define SUPPORT_ARCH_$$a 1"; \
	  done; \
	  echo '#define SUPPORT_ARCH_riscv32 0'; \
	  echo '#define ALL_SUPPORTED_ARCHS "i386 x86_64 x86_64h armv6 armv7 armv7s armv7m armv7em armv7k arm64 arm64e arm64_32 armv8m.main armv8.1m.main"'; \
	  echo '#define BITCODE_XAR_VERSION "1.0"'; \
	  echo '#define LD64_VERSION_NUM ${LD64_VERSION}'; \
	  echo '#define LD_PAGE_SIZE 0x1000'; \
	} > ${.TARGET}

LD64_VERSION?=	956.6

# compile_stubs.h wraps the compile_stubs csh script as a C string,
# exactly as the xcodeproj's script phase does.
${LD64_GEN}/compile_stubs.h: ${LD64}/compile_stubs
	@mkdir -p ${LD64_GEN}
	@echo 'static const char *compile_stubs = ' > ${.TARGET}
	@sed 's/"/\\"/g; s/^/"/; s/$$/\\n"/' ${LD64}/compile_stubs >> ${.TARGET}
	@echo ';' >> ${.TARGET}

# A shim exposing only mach-o/dyld_priv.h from lib/dyld, so that dyld's
# other headers do not shadow the system's dlfcn.h or cctools'
# mach-o/dyld.h.  dyld's header annotates with bridgeos(), a platform the
# public SDK's availability macros do not know, so the annotations are
# neutered before the include -- irrelevant for a build tool.
${LD64_GEN}/dyldshim/mach-o/dyld_priv.h:
	@mkdir -p ${LD64_GEN}/dyldshim/mach-o
	@{ \
	  echo '#include <Availability.h>'; \
	  for m in __API_AVAILABLE __API_DEPRECATED \
		   __API_DEPRECATED_WITH_REPLACEMENT __API_UNAVAILABLE; do \
	    echo "#pragma push_macro(\"$$m\")"; \
	    echo "#undef $$m"; echo "#define $$m(...)"; \
	  done; \
	  echo '#include "${TOP}/lib/dyld/include/mach-o/dyld_priv.h"'; \
	  for m in __API_AVAILABLE __API_DEPRECATED \
		   __API_DEPRECATED_WITH_REPLACEMENT __API_UNAVAILABLE; do \
	    echo "#pragma pop_macro(\"$$m\")"; \
	  done; \
	} > ${.TARGET}

# ld_classicVersionString is declared extern in Options.cpp but defined
# nowhere in the sources -- Apple's build system stamps it in.  The
# format is the classic Apple what(1) string, matching what a stock
# `ld-classic -v` prints.
${LD64_GEN}/version.c:
	@mkdir -p ${LD64_GEN}
	@echo 'const char ld_classicVersionString[] = "@(#)PROGRAM:ld  PROJECT:ld64-${LD64_VERSION}\\n";' > ${.TARGET}

# tapi/Version.inc is generated by tapi's CMake build from
# Version.inc.in; ld64 reaches it through tapi/Version.h.  The version is
# read out of tapi's own CMakeLists so it tracks the submodule.
TAPI_FULL_VERSION!=	sed -n 's/^set(TAPI_FULL_VERSION "\([^"]*\)".*/\1/p' \
			${TOP}/src/dist-dev-tools/tapi/CMakeLists.txt 2>/dev/null || echo 2.0.0

${LD64_GEN}/tapi/Version.inc:
	@mkdir -p ${LD64_GEN}/tapi
	@{ \
	  echo '#define TAPI_VERSION ${TAPI_FULL_VERSION}'; \
	  echo '#define TAPI_VERSION_MAJOR ${TAPI_FULL_VERSION:C/\..*//}'; \
	  echo '#define TAPI_VERSION_MINOR ${TAPI_FULL_VERSION:C/^[0-9]*\.//:C/\..*//}'; \
	  echo '#define TAPI_VERSION_PATCH ${TAPI_FULL_VERSION:C/^[0-9]*\.[0-9]*\.//}'; \
	} > ${.TARGET}

# libplatform's os/lock_private.h has the same bridgeos() problem as
# dyld's header, so it gets the same treatment.
${LD64_GEN}/osshim/os/lock_private.h:
	@mkdir -p ${LD64_GEN}/osshim/os
	@{ \
	  echo '#include <Availability.h>'; \
	  for m in __API_AVAILABLE __API_DEPRECATED \
		   __API_DEPRECATED_WITH_REPLACEMENT __API_UNAVAILABLE; do \
	    echo "#pragma push_macro(\"$$m\")"; \
	  done; \
	  for m in __API_AVAILABLE __API_DEPRECATED \
		   __API_DEPRECATED_WITH_REPLACEMENT __API_UNAVAILABLE; do \
	    echo "#undef $$m"; echo "#define $$m(...)"; \
	  done; \
	  echo '#include "${TOP}/lib/libplatform/private/os/lock_private.h"'; \
	  for m in __API_UNAVAILABLE __API_DEPRECATED_WITH_REPLACEMENT \
		   __API_DEPRECATED __API_AVAILABLE; do \
	    echo "#pragma pop_macro(\"$$m\")"; \
	  done; \
	} > ${.TARGET}

# Every object depends on the generated headers.
.for s in ${T_SRCS}
${T_OBJDIR}/${s:T:R}.o: ${LD64_GEN}/version.c ${LD64_GEN}/configure.h ${LD64_GEN}/compile_stubs.h \
			${LD64_GEN}/dyldshim/mach-o/dyld_priv.h \
			${LD64_GEN}/osshim/os/lock_private.h \
			${LD64_GEN}/tapi/Version.inc
.endfor
