# libxml2, from Apple's distribution.
#
# Apple ship libxml2.2.dylib, its headers in usr/include/libxml2 and
# /usr/bin/xmllint.  The drop is their Xcode project wrapped around
# upstream's tree, and upstream's tree under libxml2/ is what gets
# built: the xcodeproj drives a build this tree cannot run.
#
# There is no configure in the drop, only configure.ac, so one is
# generated first.  autoreconf is a build tool here and nothing links
# against it.
P_PREPARE=	cd libxml2 && autoreconf -fi >/dev/null 2>&1

P_CONFIGURE=	libxml2/configure

# No Python bindings, no documentation, and none of the optional
# compression or networking backends -- what is wanted is the parser,
# the headers, and xmllint.
P_CONFIGURE_ARGS=	--without-python \
			--without-lzma \
			--with-zlib \
			--with-iconv \
			--disable-shared \
			--enable-static

P_PROGS=	bin/xmllint

# The headers go into both SDKs at usr/include/libxml2, which is where
# Apple ship them and where xml2-config points: it reports the install
# prefix, so -I/usr/include/libxml2 under an -isysroot has to resolve
# inside the SDK.  xar builds that way.
#
# They come from the stage rather than the source tree because
# xmlversion.h is generated by configure and exists nowhere else.
SDKS=		Platforms/MacOSX.platform/Developer/SDKs

P_RELEASE_MERGE=	include usr/local/include \
			lib usr/local/lib \
			include/libxml2 ${SDKS}/MacOSX.sdk/usr/include/libxml2 \
			include/libxml2 ${SDKS}/MacOSX.Internal.sdk/usr/include/libxml2
