#!/bin/sh
#
# emit-targetconditionals.sh -- write a TargetConditionals.h to stdout.
#
# Nearly everything Apple writes includes this eventually, and it is the
# first thing swift-foundation stops on.  It is not a file this tree can
# take from anywhere: CoreFoundation carries one, but it says "For CF on
# Linux ONLY" at the top and defines TARGET_OS_MAC as 0, which would
# tell every consumer it is not building for a Mac.
#
# So it is written here, from what the compiler already knows.  Every
# value below is decided by a predefined macro rather than by a build
# flag, which is what makes it correct for whatever it is compiled for
# rather than for the machine that generated it.
#
# Copyright (c) 2026 Sunneva N. Mariu
# SPDX-License-Identifier: BSD-3-Clause

cat <<'HEADER'
/*
 * TargetConditionals.h -- which Apple platform is being compiled for.
 *
 * Generated by mk/scripts/emit-targetconditionals.sh.  Every value is
 * derived from a compiler predefine, so this one header is right for
 * every target it is compiled for.
 */

#ifndef __TARGETCONDITIONALS__
#define __TARGETCONDITIONALS__

#if defined(__APPLE__) && defined(__MACH__)

/* This tree builds for macOS.  The other Apple platforms are named so
   that code testing for them compiles, and answer no. */
#define TARGET_OS_MAC               1
#define TARGET_OS_OSX               1
#define TARGET_OS_DARWIN            1
#define TARGET_OS_IPHONE            0
#define TARGET_OS_IOS               0
#define TARGET_OS_MACCATALYST       0
#define TARGET_OS_TV                0
#define TARGET_OS_WATCH             0
#define TARGET_OS_VISION            0
#define TARGET_OS_BRIDGE            0
#define TARGET_OS_DRIVERKIT         0
#define TARGET_OS_SIMULATOR         0
#define TARGET_OS_EMBEDDED          0
#define TARGET_IPHONE_SIMULATOR     TARGET_OS_SIMULATOR
#define TARGET_OS_NANO              TARGET_OS_WATCH

#else

#define TARGET_OS_MAC               0
#define TARGET_OS_OSX               0
#define TARGET_OS_DARWIN            0
#define TARGET_OS_IPHONE            0
#define TARGET_OS_IOS               0
#define TARGET_OS_SIMULATOR         0

#endif /* __APPLE__ && __MACH__ */

#define TARGET_OS_WIN32             0
#define TARGET_OS_WINDOWS           0
#define TARGET_OS_UNIX              0
#define TARGET_OS_LINUX             0

/* The architecture, from the compiler's own idea of what it is. */
#if defined(__arm64__) || defined(__aarch64__)
#define TARGET_CPU_ARM              0
#define TARGET_CPU_ARM64            1
#define TARGET_CPU_X86              0
#define TARGET_CPU_X86_64           0
#elif defined(__x86_64__)
#define TARGET_CPU_ARM              0
#define TARGET_CPU_ARM64            0
#define TARGET_CPU_X86              0
#define TARGET_CPU_X86_64           1
#elif defined(__i386__)
#define TARGET_CPU_ARM              0
#define TARGET_CPU_ARM64            0
#define TARGET_CPU_X86              1
#define TARGET_CPU_X86_64           0
#elif defined(__arm__)
#define TARGET_CPU_ARM              1
#define TARGET_CPU_ARM64            0
#define TARGET_CPU_X86              0
#define TARGET_CPU_X86_64           0
#else
#define TARGET_CPU_ARM              0
#define TARGET_CPU_ARM64            0
#define TARGET_CPU_X86              0
#define TARGET_CPU_X86_64           0
#endif

#define TARGET_CPU_PPC              0
#define TARGET_CPU_PPC64            0
#define TARGET_CPU_MIPS             0
#define TARGET_CPU_SPARC            0
#define TARGET_CPU_ALPHA            0

/* Word size and byte order, likewise. */
#if defined(__LP64__) || defined(_LP64)
#define TARGET_RT_64_BIT            1
#else
#define TARGET_RT_64_BIT            0
#endif

#if defined(__LITTLE_ENDIAN__) || \
    (defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
#define TARGET_RT_LITTLE_ENDIAN     1
#define TARGET_RT_BIG_ENDIAN        0
#else
#define TARGET_RT_LITTLE_ENDIAN     0
#define TARGET_RT_BIG_ENDIAN        1
#endif

#define TARGET_RT_MAC_CFM           0
#define TARGET_RT_MAC_MACHO         1

#define TARGET_ABI_USES_IOS_VALUES  (!TARGET_CPU_X86_64 || TARGET_OS_IPHONE)

#endif /* __TARGETCONDITIONALS__ */
HEADER
